In [1]:
#Importing libraries
import pandas as pd
import numpy as np

In [3]:
#Loading the dataset

df  = pd.read_csv("Employee.csv")
df.head()

   ID   Name   Age  Department    Salary  Experience_Years
0   1  Grace  16.0     Finance  76651.76               4.3
1   2    NaN  39.0  Operations  53930.94               2.2
2   3   Omar  19.0          HR  54156.98               3.1
3   4  Kiran  28.0  Operations  75779.70               7.0
4   5    NaN  39.0     Finance  48553.13               3.0

In [8]:
#Dataset Information
print("Shape of Dataset: " , df.shape)
print("\nInformation: ",df.info())
print("\nMissing Value: " , df.isnull().sum())
print("\nDuplicate Records: " , df.duplicated().sum())

Shape of Dataset:  (1250, 6)
<class 'pandas.DataFrame'>
RangeIndex: 1250 entries, 0 to 1249
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                1250 non-null   int64
 1   Name              1190 non-null   str
 2   Age               1187 non-null   float64
 3   Department        1250 non-null   str
 4   Salary            1186 non-null   float64
 5   Experience_Years  1250 non-null   float64
dtypes: float64(3), int64(1), str(2)
memory usage: 71.0 KB

Information:  None

Missing Value:  ID                   0
Name                60
Age                 63
Department           0
Salary              64
Experience_Years     0
dtype: int64

Duplicate Records:  49

In [ ]:
#Removing Duplicate Records

df = df.drop_duplicates()
print(df.shape)

(1201, 6)

In [12]:
#Handle Missing Values

for column in df.columns:
    if df[column].dtype in ['int64' , 'float64']:
        df[column].fillna(df[column].median(),inplace=True)
    else:
        df[column].fillna("Unknown" , inplace=True)
print(df.isnull().sum())

ID                   0
Name                60
Age                 60
Department           0
Salary              60
Experience_Years     0
dtype: int64

C:\Users\adity\AppData\Local\Temp\ipykernel_24404\3349745599.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[column].fillna(df[column].median(),inplace=True)
C:\Users\adity\AppData\Local\Temp\ipykernel_24404\3349745599.py:7: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[column].fillna("Unknown" , inplace=True)
C:\Users\adity\AppData\Local\Temp\ipykernel_24404\3349745599.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[column].fillna(df[column].median(),inplace=True)
C:\Users\adity\AppData\Local\Temp\ipykernel_24404\3349745599.py:7: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[column].fillna("Unknown" , inplace=True)
C:\Users\adity\AppData\Local\Temp\ipykernel_24404\3349745599.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[column].fillna(df[column].median(),inplace=True)
C:\Users\adity\AppData\Local\Temp\ipykernel_24404\3349745599.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[column].fillna(df[column].median(),inplace=True)

In [13]:
#Removing extra spaces

for column in df.select_dtypes(include='object').columns:
    df[column] = df[column].str.strip()
df.head()

C:\Users\adity\AppData\Local\Temp\ipykernel_24404\3309908028.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in df.select_dtypes(include='object').columns:

   ID   Name   Age  Department    Salary  Experience_Years
0   1  Grace  16.0     Finance  76651.76               4.3
1   2    NaN  39.0  Operations  53930.94               2.2
2   3   Omar  19.0          HR  54156.98               3.1
3   4  Kiran  28.0  Operations  75779.70               7.0
4   5    NaN  39.0     Finance  48553.13               3.0

In [14]:
#Standardize Text Format

for column in df.select_dtypes(include='object').columns:
    df[column] = df[column].str.title()
df.head()

C:\Users\adity\AppData\Local\Temp\ipykernel_24404\2265589854.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in df.select_dtypes(include='object').columns:

   ID   Name   Age  Department    Salary  Experience_Years
0   1  Grace  16.0     Finance  76651.76               4.3
1   2    NaN  39.0  Operations  53930.94               2.2
2   3   Omar  19.0          Hr  54156.98               3.1
3   4  Kiran  28.0  Operations  75779.70               7.0
4   5    NaN  39.0     Finance  48553.13               3.0

In [15]:
#Convert Numeric Columns

for column in df.columns:
    try:
        df[column] = pd.to_numeric(df[column])
    except:
        pass
df.info()

<class 'pandas.DataFrame'>
Index: 1201 entries, 0 to 1236
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                1201 non-null   int64
 1   Name              1141 non-null   str
 2   Age               1141 non-null   float64
 3   Department        1201 non-null   str
 4   Salary            1141 non-null   float64
 5   Experience_Years  1201 non-null   float64
dtypes: float64(3), int64(1), str(2)
memory usage: 77.7 KB

In [16]:
#Final Quality Check

print("Final Shape of Dataset: " , df.shape)
print("\nMissing Value: " , df.isnull().sum())
print("\nDuplicate Records: " , df.duplicated().sum())
print("\Summary Statistics:" , df.describe(include='all'))

Final Shape of Dataset:  (1201, 6)

Missing Value:  ID                   0
Name                60
Age                 60
Department           0
Salary              60
Experience_Years     0
dtype: int64

Duplicate Records:  0
\Summary Statistics:                  ID   Name          Age Department         Salary  \
count   1201.000000   1141  1141.000000       1201    1141.000000
unique          NaN     20          NaN          6            NaN
top             NaN  Alice          NaN         Hr            NaN
freq            NaN     76          NaN        223            NaN
mean     600.158201    NaN    30.609991        NaN   64783.095022
std      346.612500    NaN    10.131133        NaN   57517.600883
min        1.000000    NaN     2.000000        NaN   12182.830000
25%      300.000000    NaN    25.000000        NaN   50052.100000
50%      600.000000    NaN    30.000000        NaN   60241.940000
75%      900.000000    NaN    36.000000        NaN   70239.540000
max     1200.000000    NaN   113.000000        NaN  927591.000000

        Experience_Years
count        1201.000000
unique               NaN
top                  NaN
freq                 NaN
mean            4.913822
std             2.954887
min            -6.100000
25%             3.000000
50%             5.000000
75%             6.800000
max            16.000000

<>:6: SyntaxWarning: invalid escape sequence '\S'
<>:6: SyntaxWarning: invalid escape sequence '\S'
C:\Users\adity\AppData\Local\Temp\ipykernel_24404\1524262908.py:6: SyntaxWarning: invalid escape sequence '\S'
  print("\Summary Statistics:" , df.describe(include='all'))

In [17]:
#Save Cleaned Dataset

df.to_csv("Employee_cleaned.csv",index=False)
print("Cleaned Dataset Saved Successfully")

Cleaned Dataset Saved Successfully

In [18]:
#Display the cleaned dataset

df.head(10)

   ID   Name   Age  Department     Salary  Experience_Years
0   1  Grace  16.0     Finance   76651.76               4.3
1   2    NaN  39.0  Operations   53930.94               2.2
2   3   Omar  19.0          Hr   54156.98               3.1
3   4  Kiran  28.0  Operations   75779.70               7.0
4   5    NaN  39.0     Finance   48553.13               3.0
5   6  Grace  31.0     Finance   63733.94               2.5
6   7    Tom  37.0          It   35092.76               7.4
7   8  Kiran  35.0          It   87294.59               6.4
8   9  Kiran  40.0          Hr   78098.28               6.1
9  10  David  38.0  Operations  101251.61               3.0